### ISSUE TITLE
npm install fluent-logger doesn't work

### ISSUE THREAD

**Issue by shacharz** [fluent/fluent-logger-node#14] opened 2014-08-04 12:13 UTC
I'm on windows 8 64 bit
Python 3+ isn't supported so I switched to python 2.7.8.
This error came out:

SyntaxError: unqualified exec is not allowed in function 'namedtuple' it contains a nested function with free variables
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\software\node\node_modules\npm\node_modules\node-gyp\lib\configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "D:\\software\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
...

**Comment by cosmo0920** [comment] 2015-08-27 08:39
I try to reproduce this issue.
But I couldn't reproduce this issue.
It seems that this issue already fixed.

## Environment

* Windows 7 64bit
* nodejs v0.12.7
* npm 2.11.3
* Visual Studio Express 2013 for Desktop
* node-gyp 2.0.2

## Result

CMD>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (nod
e  rebuild )
このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有
効にするには、"/m" スイッチを追加してください。
  gcc_atomic.cpp
  object.cpp
  objectc.c
  unpack.c
  vrefbuffer.c
  zone.c
  version.c
  libmsgpack.vcxproj -> C:\Users\hatake-moz\node_modules\fluent-logger\node_mod
  ules\msgpack\build\Release\\libmsgpack.lib
  msgpack.cc
     ライブラリ C:\Users\hatake-moz\node_modules\fluent-logger\node_modules\msgp
ack\
  build\Release\msgpackBinding.lib とオブジェクト C:\Users\hatake-moz\node_modul
es\flu
  ent-logger\node_modules\msgpack\build\Release\msgpackBinding.exp を作成中
  コード生成しています。
  コード生成が終了しました。
  msgpackBinding.vcxproj -> C:\Users\hatake-moz\node_modules\fluent-logger\node
  _modules\msgpack\build\Release\\msgpackBinding.node
fluent-logger@0.2.6 node_modules\fluent-logger
└── msgpack@0.2.6 (nan@1.9.0)

**Comment by cosmo0920** [comment] 2015-08-27 08:41
To repository owner: Could you close this issue?

**Comment by edsiper** [comment] 2015-09-23 01:54
sorry for the delay. Closing this.

**Closed by edsiper** 2015-09-23 01:54 UTC

**Comment by cosmo0920** [comment] 2015-09-23 01:55
Thanks! :+1:
